#!/bin/bash

currdir="$(dirname "$0")"

pacman -Syu
pacman -S neovim nginx git less --noconfirm

useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen
mkdir /var/lib/webgen/bin
mkdir /var/lib/webgen/documents
mkdir /var/lib/webgen/HTML

mkdir /etc/nginx/sites-available
mkdir /etc/nginx/sites-enabled
ln -s /etc/ngix/sites-available/system-info.conf /etc/nginx/sites-enables/system-info.conf

chown -R webgen:webgen /var/lib/webgen
chmod -R 777 /var/lib/webgen

systemctl enable /etc/systemd/system/script_runner.service
systemctl enable /etc/systemd/system/script_runner.timer
systemctl enable nginx
systemctl enable ufw.service
